#
# Input file to create a Kubernetes deployment with a Microgateway
# Docker image including health checks
# 
# Added pull always policy
#
# Prerequisites:
#   1. Create Microgateway Docker Image
#   2. Push Microgateway Docker image to Docker registry
#   3. Create Native Service Docker Image
#   4. Push Native Service Docker image to Docker registry
#
# Execute to create a Kubernetes deployment:
#
#   kubectl create -f yml.yml
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-deployment
  labels:
    app: customer-service
spec:
  minReadySeconds: 30
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: customer-service
        imagePullPolicy: Always
        image: apiworldref:5000/customerservice:latest
        ports:
        - containerPort: 8090
