FROM store/softwareag/webmethods-microservicesruntime:10.7.0.0-alpine
COPY ./ISPKG/APIWCustomer/ /opt/softwareag/IntegrationServer/packages/APIWCustomer/
COPY ./licenseKey.xml /opt/softwareag/IntegrationServer/config/
