FROM store/softwareag/webmethods-microservicesruntime:10.4
COPY ./ISPKG/APIWCustomer/ /opt/softwareag/IntegrationServer/packages/APIWCustomer/
COPY ./licenseKey.xml /opt/softwareag/IntegrationServer/config/
